name: ConduitAutomata
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.5
      uses: actions/setup-node@v2
      with:
        python-version: 3.9.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable

    - name: Start containers
      run: docker-compose up -d

    - name: Sleep for 45 seconds
      run: sleep 45s
      shell: bash

    - name: Test with pytest
      run: |
        pytest

    - name: Collect docker logs
      uses: jwalton/gh-docker-logs@v1
      with:
        dest: './logs'

    - name: Archive execution artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docker-logs
        path: './logs'
